import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import { MenuProvider } from "./context/useMenu";

const lora = Lora({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${lora.className} antialiased dark scroll-smooth`}
        suppressHydrationWarning
      >
        <MenuProvider>{children}</MenuProvider>
      </body>
    </html>
  );
}
